### ISSUE TITLE
Getting level from configuration file

### ISSUE THREAD

**Issue by yura3d** [breeze2/vscode-phpstan#6]
Hello. Thanks for this extension, it is very useful for me.
I'm working on several projects in which different levels for phpstan is used. Level and any other settings I always set in configuration file. But this extension always overrides configuration level by passing its own level value from extension settings as an argument to phpstan:
https://github.com/breeze2/vscode-phpstan/blob/f8974f5d778afeb6235d598bb99169fcee1b7cc2/src/controller.ts#L306-L310
Because of this, when I need to change level, I'm forced to do it in 2 places (configuration file and extension settings). It would be nice to have suppress of sending level argument (for example, by entering empty string to level field in extension settings, or by additional checkbox).

**Comment by breeze2** [comment]
So, could it help you? 

```ts
if (args.level === "config") {
  // set level in config file
} else if (args.level) {
  result.push("--level=" + args.level);
} else {
  result.push("--level=max");
}
```

pr #7

**Comment by yura3d** [comment]
Yes, thanks. Hope it will be released in marketplace soon.

**Comment by breeze2** [comment]
v1.1.2 was released
